/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app.business;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.app.entity.Person;
import com.app.entity.PersonRepository;
/**
 *
 * @author root
 */
@Component("personService")
public class PersonService {
    

	@Autowired // This means to get the bean called personRepository Which is auto-generated by Spring, we will use it to handle the data
	private PersonRepository personRepository;
    
	private final Logger logger = LoggerFactory.getLogger(PersonService.class);	
	
    public String format(){
        return "You saved it!";
    }
    
    public boolean OnboardPerson(Person person) {
		Person n = new Person();
		n.setFirstName(person.getFirstName());
		n.setEmail(person.getEmail());
		personRepository.save(n);
		logger.debug("--saving person in person service--");
		return true;
    }
    
	public Person getThisUser(Integer token) {               
		return personRepository.findByPersonIndex(token); 
	}



	public Iterable<Person> getAllUsers() {
		return personRepository.findAll();
	}
    
	
}
